<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '6e5460ffd2c58f84c9bcb7654f7c4f06c917700a',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '6e5460ffd2c58f84c9bcb7654f7c4f06c917700a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => 'e6a969a640b00d8daa3c66518b0405fb41ae0c4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'reference' => '039de174cd9c17a8389754d3b877a2ed22743e18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'reference' => '4745ded9307786b730d7a60df5cb5a6c43cf95f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '2.2.4',
            'version' => '2.2.4.0',
            'reference' => 'eabf68b476ac7d0f73793aada060f1c1a9bf8979',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '38e9124049cf1a164f1e4537caf19c99bf1eb260',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.4.12',
            'version' => '1.4.12.0',
            'reference' => '1ce90ba27c42e4e44e6d8458241466380b51fa16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '4.6.6',
            'version' => '4.6.6.0',
            'reference' => '3afe303d873a4d64c62ef84de491b97b006fbdac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '2.3.8',
            'version' => '2.3.8.0',
            'reference' => 'ac8e7a3db35738d56ee9a76e78a4e03d97628983',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '13edfd8706462032c2f52b4b862974dd46b71c9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '1.3.7',
            'version' => '1.3.7.0',
            'reference' => '4e8f0da10ac5802913afc151413bc8c53b6c2716',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '42c4c2eec485ee3e159ec9884f95b431287edde4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'bc37d50fea7d017d3d340f230811c9f1d7280af4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/version' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty' => array(
            'pretty_version' => 'v3.1.28',
            'version' => '3.1.28.0',
            'reference' => 'd234f79203ca236093989c579c824a1a882d1153',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty-dev' => array(
            'pretty_version' => 'v3.1.28',
            'version' => '3.1.28.0',
            'reference' => '0a77154bf36a603a8f695001dc4f685df6ccf156',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty-lexer' => array(
            'pretty_version' => 'v3.1.28',
            'version' => '3.1.28.0',
            'reference' => '04496b4b06158475dbe634ee8f95ebd9440a9bd9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty-lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty-phpunit' => array(
            'pretty_version' => 'v3.1.28',
            'version' => '3.1.28.0',
            'reference' => '4b65d72f52d1b310686d018aa48c639252c22e8d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty-phpunit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => 'ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'reference' => '88289caa3c166321883f67fe5130188ebbb47094',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
